name: dala_flutter
description: "搭拉一个找搭子的项目"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.3
  json_annotation: ^4.8.0
  shared_preferences: ^2.2.3
  bot_toast: ^4.1.0
  sentry_flutter: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.6.0
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    # 加载目录下的所有文件
    - images/
